# config/descriptions.yaml
elite: "Elite Series – 3 Piece Combo<br><br>
<span class='text-b font-medium text-lime-300 mb-1'>
1. Elegant Album Cover<br>
2. Premium Album Box<br>
3. Matching Designer Bag<br><br>
</span>
<div class='max-w-xl mx-auto'>
  Personalized to make every delivery special. The album cover and box feature UV-printed couple names, while the matching bag carries your company logo, adding a touch of class and brand presence.
</div>
<div class='max-w-xl mx-auto text-b font-medium text-lime-300 mb-1'>
  <br>UV printing details<br>
</div>
<span class='text-r mb-1'>
1. Couple name on cover<br>
2. Couple name on box<br>
3. Couple name on bag<br>
4. Your logo on bag<br>
</span>
"
prime: "Prime Series – 2 Piece Combo<br><br>
<span class='text-b font-medium text-lime-300 mb-1'>
1. Elegant Album Cover<br>
2. Matching Designer Bag<br><br>
</span>
<div class='max-w-xl mx-auto'>
  Personalized to make every delivery special. The album cover feature UV-printed couple names, while the matching bag carries your company logo, adding a touch of class and brand presence.
</div>
<div class='max-w-xl mx-auto text-b font-medium text-lime-300 mb-1'>
  <br>UV printing details<br>
</div>
<span class='text-r mb-1'>
1. Couple name on cover<br>
2. Couple name on bag<br>
3. Your logo on bag<br>
</span>
"

classic: "Classic Series – Evergreen Box Combos <br><br>
<span class='text-b font-medium text-lime-300 mb-1'>
1. Elegant Album Cover<br>
2. Matching Designer Box<br><br>
</span>
<div class='max-w-xl mx-auto'>
A premium album and matching box combo, both featuring large acrylic panels on the cover and lid for a bold, modern look. The big acrylic pieces provide striking coverage, giving the set a sleek, high-end finish that makes your memories stand out beautifully.
</div>
"